### ISSUE TITLE
Picking game file location not possible

### ISSUE THREAD

**Issue by AASluke** [Ipmake/kocitylauncher#3]
![grafik](https://github.com/Ipmake/kocitylauncher/assets/50229511/79abb73d-5a98-4b3b-abb8-373c2a7f25a4)

When I click CHANGE under Settings > Game Directory, the Windows Explorer opens, but no matter where I point it the error message above appears.
Please let me know if I can provide further information.

**Comment by Ipmake** [comment]
Alright, the issue was related to checking the previous directory for traces of an install, which obviously didn't exist cause you have a fresh install. Here's the commit for other devs: f0419fc

You can now get the new version by using the auto updater of the launcher (that runs on startup of the launcher) or in the latest release here: https://github.com/Ipmake/kocitylauncher/releases/tag/v0.3.2-beta
